
name: Go Build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Build
        run: make build